version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn package
      - ls -hal
artifacts:
  files:
    - target/*
    - scripts/*
    - appspec.yml
